POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"milena@gmail.com",
    "password": "Cid3ne7",
    "malware" : "exec evilCorp.py"
}
###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"milena@gmail.com",
    "password": "Cid3ne7"
}

### get the currently session user 
GET http://localhost:3000/auth/whoami
### sign out
POST  http://localhost:3000/auth/signout
###  Get one user by id
GET http://localhost:3000/auth/2
### Get users by conditions
GET http://localhost:3000/auth?email=diana@gmail.com
###
DELETE http://localhost:3000/auth/8

###
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{   
    "password": "RealidadINVERSA3X8",
    "email":"xcamor@udea.edu.co"
}

# ###
# GET http://localhost:3000/auth/colors/red

# ###
# GET http://localhost:3000/auth/colors